"""create user_profiles table

Revision ID: 235906aede35
Revises: 
Create Date: 2026-09-14 13:19:48.283642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235906aede35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('skin_type', sa.String(), nullable=True),
    sa.Column('skin_undertone', sa.String(), nullable=True),
    sa.Column('seasonal_color_type', sa.String(), nullable=True),
    sa.Column('body_shape', sa.String(), nullable=True),
    sa.Column('style_archetype', sa.String(), nullable=True),
    sa.Column('palette_name', sa.String(), nullable=True),
    sa.Column('palette_swatches', sa.JSON(), nullable=True),
    sa.Column('preferred_styles', sa.JSON(), nullable=True),
    sa.Column('body_shape_tips', sa.JSON(), nullable=True),
    sa.Column('wardrobe_insights', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
